version: '3.7'
services:
        slips:
                image: stratosphereips/slips:latest
                container_name: Slips
                cap_add:
                  - NET_ADMIN
                volumes:
                  - type: bind
                    source: ./config
                    target: /StratosphereLinuxIPS/config/
                    read_only: true
                  - type: bind
                    source: ./dataset
                    target: /StratosphereLinuxIPS/dataset/
                    read_only: true
                network_mode: "host"
                entrypoint: ["/bin/bash"]
